get:
  operationId: get_provider_configuration
  summary: Get provider cluster configuration
  description: Returns the provider cluster configuration.
  x-onedata-version: 3
  x-onedata-module: rest_service
  x-onedata-resource: service_oneprovider
  x-onedata-noauth: true
  tags:
    - Oneprovider
  produces:
    - application/json
  responses:
    '200':
      description: The provider cluster configuration.
      schema:
        $ref: '#/definitions/ProviderConfiguration'
    '401':
      description: Unauthorized request.
    '403':
      description: Forbidden request.
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
        

post:
  operationId: configure_provider
  summary: Configure provider deployment
  description: >
    Configures and starts provider services, such as database, cluster manager
    and cluster worker. Depending on the configuration, sets up provider storage
    and registers in the zone.

    This request can be executed unauthorized as long as there are no admin users.
  x-onedata-version: 3
  x-onedata-module: rest_service
  x-onedata-resource: service_oneprovider
  x-onedata-noauth: true
  tags:
    - Oneprovider
  consumes:
    - application/json
  responses:
    '201':
      description: Deployment process successfully started.
      headers:
        Location:
          type: string
          description: >
            The path to the task resource, which can be queried to check 
            operation status.
    '400':
      description: Invalid request.
      schema:
        $ref: '#/definitions/Error'
    '403':
      description: Forbidden request.
    '500':
      description: Internal server error.
      schema:
        $ref: '#/definitions/Error'
  parameters:
  - name: providerConfiguration
    in: body
    description: The provider configuration description.
    schema:
      $ref: '#/definitions/ProviderConfiguration'
    required: true